/**
 * Builds the environment file that ships inside the packaged app.
 *
 * A Firebase *web* config is public by design — it identifies the project, it
 * doesn't authorise anything — so those values are copied through. The admin
 * allowlist is not: a copy you hand to someone else should not inherit who
 * your administrators are.
 *
 * Allowlist rather than denylist on purpose. A secret added to desktop/.env
 * later cannot leak by default; it simply isn't copied.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = path.join(root, ".env");
const OUT = path.join(root, "build", "app.env");

/** Safe to ship: project identity and two behaviour switches. */
const ALLOWLIST = [
  "JARVIS_FIREBASE_API_KEY",
  "JARVIS_FIREBASE_AUTH_DOMAIN",
  "JARVIS_FIREBASE_PROJECT_ID",
  "JARVIS_FIREBASE_APP_ID",
  "JARVIS_REQUIRE_AUTH",
  "JARVIS_ENABLE_2FA",
];

/** Minimal dotenv reader — enough for the KEY=VALUE files in this repo. */
function readEnv(file) {
  if (!existsSync(file)) return {};
  const out = {};
  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    const match = /^\s*(?:export\s+)?([A-Z0-9_]+)\s*=\s*(.*)$/i.exec(line);
    if (!match) continue;
    let value = match[2].trim();
    if (/^(["']).*\1$/.test(value)) value = value.slice(1, -1);
    else value = value.replace(/\s+#.*$/, "").trim();
    out[match[1]] = value;
  }
  return out;
}

const local = readEnv(SOURCE);
const shipped = {};
for (const key of ALLOWLIST) {
  if (local[key]) shipped[key] = local[key];
}

// Requiring sign-in with no project to sign in against would lock every copy
// out of its own microphone. Refuse to ship that combination.
if (shipped.JARVIS_REQUIRE_AUTH === "true" && !shipped.JARVIS_FIREBASE_PROJECT_ID) {
  console.warn(
    "make-app-env: JARVIS_REQUIRE_AUTH=true but no Firebase project is configured —\n" +
      "  shipping it as false, since the packaged app would have no way to sign\n" +
      "  anyone in. Fill in desktop/.env to enable the sign-in gate."
  );
  shipped.JARVIS_REQUIRE_AUTH = "false";
}

const withheld = Object.keys(local).filter((k) => !(k in shipped));

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  [
    "# GENERATED by desktop/scripts/make-app-env.mjs - do not edit.",
    "#",
    "# The public Firebase identity shipped inside the packaged app. The admin",
    "# allowlist is deliberately absent.",
    "",
    ...Object.entries(shipped).map(([k, v]) => `${k}=${v}`),
    "",
  ].join("\n")
);

console.log(`Wrote ${OUT}`);
console.log(`  shipped : ${Object.keys(shipped).join(", ") || "(nothing)"}`);
console.log(`  withheld: ${withheld.join(", ") || "(nothing)"}`);
